### ISSUE TITLE
Systemidee auf Wiki-Startseite darstellen

### ISSUE THREAD

**Issue by Matze985** [sweIhm/sweiproject-tg2b-7#4]
Die Systemidee soll auf der Wiki Startseite dargestellt werden.
Dazu sind folgende Fragen zu klären:

### Identifizieren der Zielsetzung des Systementwicklungsprojektes
- Was ist das auslösende Problem?
- Was soll mit dem neuen System erreicht werden?
- Welche Visionen werden verfolgt?

### Entwickeln der Systemidee
- Vision fixieren, ausformulieren und festschreiben als Systemidee
- Mindestinformation
    - Wichtige Eigenschaften und Leistungsmerkmale
    - Grenzen der Entwicklungsaufgabe und des Systems
    - Ggf. Voraussetzungen und Rahmenbedingungen
- Konsens schaffen über die Systemidee zwischen Auftraggeber, Anwendern und Entwicklern

Siehe dazu auch [Vorlesungsfolien](https://moodle.hm.edu/pluginfile.php/236776/mod_resource/content/8/03-Analyse.pdf)

**Comment by walkmario** [comment]
Systemidee verfasst, durchgängige Benennung mit Anwendungsfällen.
